---
driver:
  name: podman

platforms:
  - name: vector-almalinux
    image: almalinux:8
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    environment:
      container: podman
    ansible_python_interpreter: /usr/bin/python3

provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
  env:
    ANSIBLE_PYTHON_INTERPRETER: auto_silent
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
  playbooks:
    converge: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/converge.yml
    verify: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/verify.yml

verifier:
  name: ansible
