[tox]
minversion = 3.4
envlist = py39-ansible{214,215}
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible214: ansible-core>=2.14,<2.15
    ansible215: ansible-core>=2.15,<2.16
commands =
    {posargs:molecule test -s compatibility --destroy always}
